import authRoutes from '../routes/authRoutes.js';
console.log('✅ authRoutes');
import agentRoutes from '../routes/agentRoutes.js';
console.log('✅ agentRoutes');
import sessionRoutes from '../routes/sessionRoutes.js';
console.log('✅ sessionRoutes');
import ticketRoutes from '../routes/ticketRoutes.js';
console.log('✅ ticketRoutes');
import analyticsRoutes from '../routes/analyticsRoutes.js';
console.log('✅ analyticsRoutes');
import supervisorRoutes from '../routes/supervisorRoutes.js';
console.log('✅ supervisorRoutes');
import broadcastRoutes from '../routes/broadcastRoutes.js';
console.log('✅ broadcastRoutes');
import fileRoutes from '../routes/fileRoutes.js';
console.log('✅ fileRoutes');
import errorHandler from '../middleware/errorHandler.js';
console.log('✅ errorHandler');
import { connectDb } from '../db.js';
console.log('✅ db');
import passportConfig from '../passport.js';
console.log('✅ passport');
