import React from 'react';

export const getStatusColor = (status: string) => {
    switch (status) {
        case 'ACTIVE': return '#10b981';
        case 'ON_CALL': return '#3b82f6'; // var(--accent-blue) fallback
        case 'ON_BREAK': return '#facc15'; // var(--accent-yellow) fallback
        default: return '#475569'; // var(--text-muted) fallback
    }
};

export const styles: Record<string, React.CSSProperties> = {
    appLayout: {
        display: 'flex',
        minHeight: '100vh',
        background: 'var(--bg-deep)',
        color: 'var(--text-primary)',
        fontFamily: "'Inter', sans-serif",
    },
    sideNav: {
        width: '280px',
        background: 'var(--bg-card)',
        borderRight: '1px solid var(--glass-border)',
        display: 'flex',
        flexDirection: 'column',
        padding: '1.5rem',
        position: 'sticky',
        top: 0,
        height: '100vh',
    },
    navHeader: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        marginBottom: '2.5rem',
        padding: '0.5rem',
    },
    logoBox: {
        width: '40px',
        height: '40px',
        background: 'var(--glass-highlight)',
        borderRadius: '10px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    navLogo: {
        fontSize: '1.2rem',
        fontWeight: '800',
        letterSpacing: '0.05em',
        color: 'var(--accent-yellow)',
    },
    navLinks: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
        flex: 1,
    },
    navItem: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        padding: '12px 16px',
        borderRadius: '10px',
        border: 'none',
        background: 'transparent',
        color: 'var(--text-secondary)',
        fontSize: '0.9rem',
        fontWeight: '600',
        cursor: 'pointer',
        textAlign: 'left',
        width: '100%',
        transition: 'all 0.2s',
    },
    navItemActive: {
        background: 'var(--glass-highlight)',
        color: 'var(--accent-yellow)',
    },
    navFooter: {
        paddingTop: '1.5rem',
        borderTop: '1px solid var(--glass-border)',
        display: 'flex',
        flexDirection: 'column',
        gap: '1rem',
    },
    miniProfile: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
    },
    avatar: {
        width: '36px',
        height: '36px',
        background: 'var(--accent-blue)',
        color: '#fff',
        borderRadius: '50%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontWeight: '700',
        fontSize: '0.9rem',
    },
    profileText: {
        display: 'flex',
        flexDirection: 'column',
    },
    profileName: {
        fontSize: '0.85rem',
        fontWeight: '700',
        color: 'var(--text-primary)',
    },
    profileId: {
        fontSize: '0.7rem',
        color: 'var(--text-muted)',
        fontFamily: 'monospace',
    },
    logoutBtn: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        padding: '8px',
        color: 'var(--accent-error)',
        background: 'transparent',
        border: 'none',
        fontSize: '0.8rem',
        fontWeight: '600',
        cursor: 'pointer',
    },
    mainContainer: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        overflowX: 'hidden',
    },
    topHeader: {
        height: '80px',
        background: 'var(--bg-card)',
        borderBottom: '1px solid var(--glass-border)',
        padding: '0 2.5rem',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        position: 'sticky',
        top: 0,
        zIndex: 10,
    },
    headerTitle: {
        display: 'flex',
        flexDirection: 'column',
    },
    viewTitle: {
        fontSize: '1.25rem',
        fontWeight: '800',
        color: 'var(--text-primary)',
        textTransform: 'capitalize',
    },
    breadcrumb: {
        fontSize: '0.75rem',
        color: 'var(--text-muted)',
        fontWeight: '500',
    },
    headerActions: {
        display: 'flex',
        alignItems: 'center',
        gap: '2rem',
    },
    globalStats: {
        display: 'flex',
        alignItems: 'center',
        gap: '1.5rem',
    },
    statBox: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        fontSize: '0.85rem',
        fontWeight: '700',
        color: 'var(--text-secondary)',
        background: 'var(--glass-highlight)',
        padding: '6px 12px',
        borderRadius: '8px',
        border: '1px solid var(--glass-border)',
    },
    statusBadge: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        fontSize: '0.75rem',
        fontWeight: '800',
        textTransform: 'uppercase',
        letterSpacing: '0.05em',
        padding: '6px 12px',
        background: 'var(--glass-highlight)',
        borderRadius: '8px',
        color: 'var(--text-secondary)',
        border: '1px solid var(--glass-border)',
    },
    statusDot: {
        width: '8px',
        height: '8px',
        borderRadius: '50%',
    },
    viewContent: {
        padding: '2.5rem',
        flex: 1,
    },
    dashboardView: {
        display: 'flex',
        flexDirection: 'column',
        gap: '2.5rem',
    },
    kpiGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
        gap: '1.5rem',
    },
    kpiCard: {
        padding: '1.5rem',
        display: 'flex',
        alignItems: 'center',
        gap: '1.25rem',
        background: 'var(--bg-card)',
        borderRadius: '16px',
        border: '1px solid var(--glass-border)',
        boxShadow: 'none',
    },
    kpiIcon: {
        width: '48px',
        height: '48px',
        borderRadius: '12px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    kpiText: {
        display: 'flex',
        flexDirection: 'column',
    },
    kpiLabel: {
        fontSize: '0.75rem',
        fontWeight: '600',
        color: 'var(--text-secondary)',
        textTransform: 'uppercase',
        letterSpacing: '0.05em',
    },
    kpiValue: {
        fontSize: '1.5rem',
        fontWeight: '800',
        color: 'var(--text-primary)',
    },
    sectionCard: {
        padding: '1.5rem',
        background: 'var(--bg-card)',
        borderRadius: '16px',
        border: '1px solid var(--glass-border)',
        boxShadow: 'none',
    },
    sectionHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '1.5rem',
    },
    sectionTitle: {
        fontSize: '1rem',
        fontWeight: '800',
        color: 'var(--text-primary)',
    },
    metricsContainer: {
        display: 'flex',
        flexDirection: 'column',
        gap: '1.5rem',
    },
    metricItem: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
    },
    metricMeta: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    metricLabel: {
        fontSize: '0.9rem',
        fontWeight: '700',
        color: 'var(--text-secondary)',
    },
    metricPercent: {
        fontSize: '0.9rem',
        fontWeight: '800',
        color: 'var(--accent-blue)',
    },
    barBg: {
        height: '8px',
        background: 'var(--glass-highlight)',
        borderRadius: '4px',
        overflow: 'hidden',
    },
    barFill: {
        height: '100%',
        borderRadius: '4px',
        transition: 'width 1s ease-in-out',
        background: 'var(--accent-blue)',
    },
    metricDesc: {
        fontSize: '0.75rem',
        color: 'var(--text-muted)',
        fontWeight: '500',
    },
    searchBar: {
        display: 'flex',
        alignItems: 'center',
        gap: '10px',
        background: 'var(--glass-highlight)',
        padding: '8px 16px',
        borderRadius: '10px',
        border: '1px solid var(--glass-border)',
        width: '300px',
    },
    lightInput: {
        border: 'none',
        background: 'transparent',
        fontSize: '0.85rem',
        color: 'var(--text-primary)',
        outline: 'none',
        width: '100%',
    },
    statsHero: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
        gap: '1.5rem',
        marginBottom: '2rem',
    },
    heroCard: {
        padding: '1.25rem',
        display: 'flex',
        alignItems: 'center',
        gap: '1.25rem',
        background: 'var(--bg-card)',
        borderRadius: '16px',
        border: '1px solid var(--glass-border)',
        boxShadow: 'none',
    },
    heroIcon: {
        width: '44px',
        height: '44px',
        borderRadius: '12px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    heroText: {
        display: 'flex',
        flexDirection: 'column',
    },
    heroLabel: {
        fontSize: '0.75rem',
        fontWeight: '700',
        color: 'var(--text-secondary)',
        textTransform: 'uppercase',
        letterSpacing: '0.05em',
    },
    heroValue: {
        fontSize: '1.25rem',
        fontWeight: '800',
        color: 'var(--text-primary)',
    },
    dashboardGrid: {
        display: 'grid',
        gridTemplateColumns: '1fr 300px',
        gap: '2rem',
        alignItems: 'start',
    },
    mainMetricsCol: {
        display: 'flex',
        flexDirection: 'column',
    },
    sidebarCol: {
        height: '100%',
    },
    breakList: {
        marginTop: '1.25rem',
        display: 'flex',
        flexDirection: 'column',
        gap: '0.75rem',
    },
    breakRow: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '12px 16px',
        background: 'var(--glass-highlight)',
        borderRadius: '10px',
    },
    breakTimeInfo: {
        display: 'flex',
        flexDirection: 'column',
    },
    breakTimeLabel: {
        fontSize: '0.85rem',
        fontWeight: '700',
        color: 'var(--text-primary)',
    },
    breakDuration: {
        fontSize: '0.75rem',
        color: 'var(--text-muted)',
        fontWeight: '600',
    },
    emptyActivity: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '12px',
        padding: '3rem 0',
        color: 'var(--text-muted)',
        fontWeight: '700',
        fontSize: '0.8rem',
    },
    ticketTable: {
        display: 'flex',
        flexDirection: 'column',
        gap: '1px',
        background: 'var(--glass-border)',
        borderRadius: '12px',
        overflow: 'hidden',
        border: '1px solid var(--glass-border)',
    },
    tableRow: {
        background: 'var(--bg-card)',
        padding: '1.25rem 1.5rem',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    rowMain: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
        flex: 1,
    },
    rowHeader: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
    },
    rowId: {
        fontSize: '0.9rem',
        fontWeight: '800',
        color: 'var(--accent-blue)',
        fontFamily: 'monospace',
    },
    rowType: {
        fontSize: '0.7rem',
        fontWeight: '700',
        color: 'var(--text-secondary)',
        background: 'var(--glass-highlight)',
        padding: '2px 8px',
        borderRadius: '4px',
        textTransform: 'uppercase',
    },
    rowStatus: {
        fontSize: '0.7rem',
        fontWeight: '800',
        padding: '2px 10px',
        borderRadius: '100px',
        textTransform: 'uppercase',
    },
    rowDesc: {
        fontSize: '0.9rem',
        color: 'var(--text-secondary)',
        lineHeight: '1.5',
    },
    rowFooter: {
        display: 'flex',
        alignItems: 'center',
        gap: '6px',
        fontSize: '0.75rem',
        color: 'var(--text-muted)',
        fontWeight: '600',
    },
    lightPagination: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '1.5rem',
        marginTop: '1.5rem',
    },
    pagBtn: {
        padding: '6px 16px',
        borderRadius: '8px',
        border: '1px solid var(--glass-border)',
        background: 'var(--bg-card)',
        color: 'var(--text-secondary)',
        fontSize: '0.8rem',
        fontWeight: '600',
        cursor: 'pointer',
    },
    pagInfo: {
        fontSize: '0.8rem',
        color: 'var(--text-muted)',
        fontWeight: '600',
    },
    opsGrid: {
        display: 'grid',
        gridTemplateColumns: '400px 1fr',
        gap: '2rem',
        height: '100%',
    },
    opsControls: {
        display: 'flex',
        flexDirection: 'column',
    },
    ctrlGrid: {
        display: 'grid',
        gridTemplateColumns: '1fr 1fr',
        gap: '1rem',
    },
    ctrlBtn: {
        padding: '1.25rem 0.75rem',
        borderRadius: '12px',
        background: 'var(--glass-highlight)',
        border: '1px solid var(--glass-border)',
        color: 'var(--text-secondary)',
        fontWeight: '700',
        fontSize: '0.8rem',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: '8px',
        cursor: 'pointer',
        transition: 'all 0.2s',
        boxShadow: 'none',
    },
    lightForm: {
        display: 'flex',
        flexDirection: 'column',
        gap: '1.25rem',
    },
    fieldGroup: {
        display: 'flex',
        flexDirection: 'column',
        gap: '6px',
    },
    lightLabel: {
        fontSize: '0.75rem',
        fontWeight: '700',
        color: 'var(--text-muted)',
        textTransform: 'uppercase',
    },
    lightSelect: {
        padding: '12px',
        borderRadius: '10px',
        border: '1px solid var(--glass-border)',
        background: 'var(--bg-deep)',
        fontSize: '0.9rem',
        color: 'var(--text-primary)',
        outline: 'none',
    },
    lightTextarea: {
        padding: '12px',
        borderRadius: '10px',
        border: '1px solid var(--glass-border)',
        background: 'var(--bg-deep)',
        fontSize: '0.9rem',
        color: 'var(--text-primary)',
        minHeight: '120px',
        resize: 'none',
        outline: 'none',
    },
    primaryBtn: {
        padding: '12px',
        borderRadius: '10px',
        background: 'var(--accent-blue)',
        color: '#fff',
        border: 'none',
        fontWeight: '700',
        fontSize: '0.9rem',
        cursor: 'pointer',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '8px',
        boxShadow: 'none',
    },
    opsQueue: {
        height: '100%',
    },
    queueCount: {
        fontSize: '0.75rem',
        fontWeight: '800',
        color: 'var(--accent-blue)',
        background: 'var(--glass-highlight)',
        padding: '2px 10px',
        borderRadius: '100px',
    },
    queueScroll: {
        flex: 1,
        overflowY: 'auto',
        display: 'flex',
        flexDirection: 'column',
        gap: '1.25rem',
        paddingRight: '8px',
    },
    queueCard: {
        background: 'var(--bg-card)',
        border: '1px solid var(--glass-border)',
        borderRadius: '12px',
        padding: '1.25rem',
        display: 'flex',
        flexDirection: 'column',
        gap: '12px',
        boxShadow: 'none',
    },
    qHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    qId: {
        fontSize: '0.85rem',
        fontWeight: '800',
        color: 'var(--accent-blue)',
        fontFamily: 'monospace',
    },
    qTag: {
        fontSize: '0.65rem',
        fontWeight: '800',
        padding: '2px 8px',
        borderRadius: '4px',
        textTransform: 'uppercase',
    },
    qDesc: {
        fontSize: '0.85rem',
        color: 'var(--text-secondary)',
        lineHeight: '1.4',
    },
    qActions: {
        display: 'flex',
        gap: '1rem',
        marginTop: '0.5rem',
    },
    qBtn: {
        flex: 1,
        padding: '8px',
        borderRadius: '6px',
        background: 'transparent',
        border: '1px solid var(--accent-blue)',
        color: 'var(--accent-blue)',
        fontWeight: '700',
        fontSize: '0.75rem',
        cursor: 'pointer',
    },
    status_ASSIGNED: { background: 'var(--glass-highlight)', color: 'var(--accent-error)' },
    status_IN_PROGRESS: { background: 'var(--glass-highlight)', color: 'var(--accent-blue)' },
    status_RESOLUTION_REQUESTED: { background: 'var(--glass-highlight)', color: 'var(--accent-yellow)' },
    emptyView: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '1rem',
        color: 'var(--text-muted)',
        fontWeight: '700',
        fontSize: '0.9rem',
    },
    profileCard: {
        overflow: 'hidden',
        position: 'relative',
    },
    profileCover: {
        height: '160px',
        background: 'linear-gradient(135deg, #2563eb 0%, #7c3aed 100%)',
    },
    profileMeta: {
        padding: '0 2rem',
        marginTop: '-40px',
        display: 'flex',
        alignItems: 'flex-end',
        gap: '1.5rem',
        marginBottom: '2rem',
    },
    largeAvatar: {
        width: '100px',
        height: '100px',
        borderRadius: '24px',
        background: '#fff',
        border: '4px solid #fff',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '2.5rem',
        fontWeight: '800',
        color: '#2563eb',
    },
    profileMainInfo: {
        paddingBottom: '10px',
    },
    profileDisplayName: {
        fontSize: '1.5rem',
        fontWeight: '800',
        color: 'var(--text-primary)',
    },
    profileTitleBadge: {
        fontSize: '0.8rem',
        fontWeight: '600',
        color: 'var(--text-muted)',
    },
    profileDetailsGrid: {
        display: 'grid',
        gridTemplateColumns: '1fr 1fr',
        gap: '2rem',
        padding: '0 2rem',
        marginBottom: '2.5rem',
    },
    detailItem: {
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
    },
    detailLabel: {
        fontSize: '0.75rem',
        fontWeight: '700',
        color: 'var(--text-muted)',
        textTransform: 'uppercase',
    },
    detailValue: {
        fontSize: '1rem',
        fontWeight: '700',
        color: 'var(--text-primary)',
    },
    profileActions: {
        padding: '2rem',
        borderTop: '1px solid var(--glass-border)',
        display: 'flex',
        justifyContent: 'flex-end',
    },
    dangerBtn: {
        padding: '10px 20px',
        borderRadius: '10px',
        background: 'var(--glass-highlight)',
        color: 'var(--accent-error)',
        border: '1px solid var(--accent-error)',
        fontWeight: '700',
        fontSize: '0.85rem',
        cursor: 'pointer',
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
    },
    loading: {
        height: '100vh',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        background: 'var(--bg-deep)',
        color: 'var(--accent-blue)',
        fontSize: '0.9rem',
        fontWeight: '800',
        letterSpacing: '0.1em',
    }
};
