import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
    dashboard: {
        minHeight: '100vh',
        display: 'flex',
        flexDirection: 'column',
        padding: '1.5rem',
        maxWidth: '1440px',
        margin: '0 auto',
        gap: '1.5rem',
    },
    header: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: '1rem 0',
    },
    logoGroup: {
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
    },
    logo: {
        fontSize: '1.5rem',
        fontWeight: '900',
        color: 'var(--accent-yellow)',
        letterSpacing: '-0.02em',
        textTransform: 'uppercase',
    },
    badge: {
        fontSize: '0.6rem',
        background: 'rgba(250, 204, 21, 0.1)',
        color: 'var(--accent-yellow)',
        padding: '2px 8px',
        borderRadius: '4px',
        letterSpacing: '0.1em',
        fontWeight: '700',
        width: 'fit-content',
    },
    statsRow: {
        display: 'flex',
        gap: '2rem',
    },
    statCard: {
        display: 'flex',
        alignItems: 'center',
        gap: '1rem',
    },
    statIcon: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    statInfo: {
        display: 'flex',
        flexDirection: 'column',
    },
    statLabel: {
        fontSize: '0.65rem',
        color: 'var(--text-muted)',
        textTransform: 'uppercase',
        letterSpacing: '0.1em',
        fontWeight: '700',
    },
    statValue: {
        fontSize: '1.25rem',
        fontWeight: '800',
        color: 'var(--text-primary)',
    },
    logoutBtn: {
        background: 'transparent',
        border: '1px solid var(--glass-border)',
        color: 'var(--text-primary)',
        padding: '0.5rem 1rem',
        borderRadius: '8px',
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        fontSize: '0.8rem',
        fontWeight: '600',
    },
    main: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        gap: '1rem',
    },
    controlBar: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    searchBox: {
        position: 'relative',
        display: 'flex',
        alignItems: 'center',
        background: 'var(--bg-card)',
        border: '1px solid var(--glass-border)',
        borderRadius: '10px',
        padding: '0 12px',
        width: '300px',
    },
    searchInput: {
        background: 'transparent',
        border: 'none',
        padding: '10px',
        color: 'var(--text-primary)',
        outline: 'none',
        fontSize: '0.8rem',
        fontWeight: '600',
        flex: 1,
    },
    gridWrapper: {
        maxHeight: 'calc(4 * 148px + 3 * 1rem)',
        overflowY: 'auto',
        overflowX: 'hidden',
        paddingRight: '4px',
        scrollbarWidth: 'thin' as const,
    },
    grid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(4, 1fr)',
        gap: '1rem',
    },
    agentCard: {
        padding: '1.25rem',
        display: 'flex',
        flexDirection: 'column',
        gap: '1rem',
        cursor: 'pointer',
        transition: 'transform 0.15s ease, box-shadow 0.15s ease',
    },
    agentHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
    },
    agentInfo: {
        display: 'flex',
        flexDirection: 'column',
    },
    agentName: {
        fontSize: '1.1rem',
        fontWeight: '800',
        letterSpacing: '-0.01em',
    },
    agentIdTag: {
        fontSize: '0.7rem',
        color: 'var(--text-muted)',
        fontWeight: '700',
    },
    agentId: {
        fontSize: '0.7rem',
        color: 'var(--text-muted)',
        fontWeight: '600',
    },
    forceBtn: {
        background: 'rgba(239, 68, 68, 0.1)',
        border: '1px solid rgba(239, 68, 68, 0.2)',
        color: '#ef4444',
        padding: '4px',
        borderRadius: '6px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        cursor: 'pointer',
    },
    statusDot: {
        width: '10px',
        height: '10px',
        borderRadius: '50%',
        boxShadow: '0 0 10px rgba(0,0,0,0.5)',
    },
    cardContent: {
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
    },
    statusLabel: {
        fontSize: '0.75rem',
        fontWeight: '700',
        color: 'var(--text-secondary)',
        display: 'flex',
        alignItems: 'center',
    },
    viewTabs: {
        display: 'flex',
        gap: '1rem',
        marginBottom: '1rem',
        borderBottom: '1px solid var(--glass-border)',
        paddingBottom: '0.5rem',
    },
    viewTab: {
        background: 'transparent',
        border: 'none',
        color: 'var(--text-muted)',
        fontSize: '0.9rem',
        fontWeight: '600',
        padding: '0.5rem 1rem',
    },
    activeViewTab: {
        color: 'var(--accent-yellow)',
        borderBottom: '2px solid var(--accent-yellow)',
    },
    activityLog: {
        padding: '1.5rem',
        overflowX: 'auto',
    },
    sectionTitle: {
        color: 'var(--accent-yellow)',
        marginBottom: '1rem',
        textTransform: 'uppercase',
        fontSize: '1rem',
        letterSpacing: '0.05em',
    },
    table: {
        width: '100%',
        borderCollapse: 'collapse',
    },
    th: {
        textAlign: 'left',
        padding: '1rem',
        color: 'var(--text-muted)',
        fontSize: '0.75rem',
        textTransform: 'uppercase',
        letterSpacing: '0.1em',
    },
    td: {
        padding: '1rem',
        borderTop: '1px solid var(--glass-border)',
        fontSize: '0.85rem',
    },
    tr: {
        transition: 'background 0.2s',
        cursor: 'default',
    },
    statusBadge: {
        padding: '2px 8px',
        borderRadius: '4px',
        border: '1px solid',
        fontSize: '0.7rem',
        fontWeight: '700',
    },
    iconBtn: {
        background: 'transparent',
        border: 'none',
        color: 'var(--accent-blue)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        cursor: 'pointer',
    },
    modalOverlay: {
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        background: 'rgba(0,0,0,0.8)',
        zIndex: 1000,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '1rem',
    },
    modal: {
        width: '100%',
        maxWidth: '500px',
        padding: '2rem',
        display: 'flex',
        flexDirection: 'column',
        gap: '1.5rem',
    },
    modalTitle: {
        color: 'var(--accent-yellow)',
        fontSize: '1.25rem',
        textTransform: 'uppercase',
    },
    modalContent: {
        display: 'flex',
        flexDirection: 'column',
        gap: '0.75rem',
        color: 'var(--text-secondary)',
    },
    modalActions: {
        display: 'flex',
        gap: '1rem',
        marginTop: '1rem',
    },
    actions: {
        display: 'flex',
        gap: '0.75rem',
        alignItems: 'center',
    },
    filterSelect: {
        background: 'var(--bg-card)',
        border: '1px solid var(--glass-border)',
        borderRadius: '8px',
        padding: '0.5rem 1rem',
        color: 'var(--text-primary)',
        fontSize: '0.8rem',
        fontWeight: '700',
        outline: 'none',
        cursor: 'pointer',
    },
    createBtn: {
        background: 'var(--accent-yellow)',
        color: 'black',
        border: 'none',
        padding: '0.5rem 1rem',
        borderRadius: '8px',
        fontWeight: '800',
        fontSize: '0.8rem',
        display: 'flex',
        alignItems: 'center',
        gap: '6px',
        cursor: 'pointer',
    },
    modalHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '1rem',
    },
    formGroup: {
        display: 'flex',
        flexDirection: 'column',
        gap: '0.5rem',
        marginBottom: '1rem',
    },
    label: {
        fontSize: '0.65rem',
        fontWeight: '700',
        color: 'var(--text-muted)',
        letterSpacing: '0.05em',
    },
    input: {
        background: 'var(--bg-deep)',
        border: '1px solid var(--glass-border)',
        borderRadius: '8px',
        padding: '0.75rem',
        color: 'var(--text-primary)',
        fontSize: '0.9rem',
        outline: 'none',
    },
    submitBtn: {
        background: 'var(--accent-blue)',
        color: 'white',
        border: 'none',
        padding: '1rem',
        borderRadius: '8px',
        fontWeight: '800',
        width: '100%',
        marginTop: '0.5rem',
        cursor: 'pointer',
    },
    agentDetailHeader: {
        display: 'flex',
        flexDirection: 'column',
    },
    detailGrid: {
        display: 'grid',
        gridTemplateColumns: '1fr 1fr',
        gap: '1rem',
        marginBottom: '1.5rem',
    },
    detailItem: {
        display: 'flex',
        flexDirection: 'column',
        background: 'var(--glass-bg)',
        padding: '1rem',
        borderRadius: '12px',
        border: '1px solid var(--glass-border)',
    },
    detailLabel: {
        fontSize: '0.6rem',
        color: 'var(--text-muted)',
        fontWeight: '700',
        marginBottom: '0.25rem',
    },
    detailValue: {
        fontSize: '1rem',
        fontWeight: '800',
        color: 'var(--text-primary)',
    },
    sectionDivider: {
        fontSize: '0.7rem',
        fontWeight: '800',
        color: 'var(--accent-yellow)',
        letterSpacing: '0.1em',
        marginBottom: '1rem',
        display: 'flex',
        alignItems: 'center',
        gap: '1rem',
    },
    breakTimeline: {
        display: 'flex',
        flexDirection: 'column',
        gap: '1rem',
    },
    timelineItem: {
        display: 'flex',
        gap: '1rem',
        position: 'relative',
        paddingLeft: '0.5rem',
    },
    timelinePoint: {
        width: '8px',
        height: '8px',
        borderRadius: '50%',
        background: 'var(--accent-yellow)',
        marginTop: '0.4rem',
    },
    timelineContent: {
        display: 'flex',
        flexDirection: 'column',
    },
    timelineTime: {
        fontSize: '0.85rem',
        fontWeight: '700',
        color: 'var(--text-primary)',
    },
    timelineLabel: {
        fontSize: '0.65rem',
        color: 'var(--text-muted)',
        fontWeight: '600',
    },
    emptyText: {
        fontSize: '0.8rem',
        color: 'var(--text-muted)',
        fontStyle: 'italic',
        textAlign: 'center',
        padding: '1rem',
    },
    resolveBtn: {
        background: '#10b981',
        color: 'white',
        border: 'none',
        padding: '0.75rem 1.25rem',
        borderRadius: '8px',
        fontWeight: '700',
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
    },
    closeBtn: {
        background: 'transparent',
        border: '1px solid var(--glass-border)',
        color: 'var(--text-primary)',
        padding: '0.75rem 1.25rem',
        borderRadius: '8px',
        fontWeight: '600',
        cursor: 'pointer',
    },
    rejectBtn: {
        background: 'rgba(239, 68, 68, 0.1)',
        color: '#ef4444',
        border: '1px solid rgba(239, 68, 68, 0.2)',
        padding: '0.75rem 1.25rem',
        borderRadius: '8px',
        fontWeight: '700',
        cursor: 'pointer',
    },
    workstationShell: {
        display: 'flex',
        flexDirection: 'column',
        gap: '1.25rem',
        marginTop: '0.5rem',
    },
    kpiStrip: {
        display: 'grid',
        gridTemplateColumns: 'repeat(5, 1fr)',
        gap: '1rem',
    },
    kpiCard: {
        display: 'flex',
        alignItems: 'center',
        gap: '1rem',
        padding: '1.25rem 1.5rem',
        borderRadius: '14px',
        border: '1px solid',
        transition: 'transform 0.15s',
    },
    kpiIcon: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        width: '40px',
        height: '40px',
        borderRadius: '10px',
        background: 'rgba(255,255,255,0.06)',
        flexShrink: 0,
    },
    kpiBody: {
        display: 'flex',
        flexDirection: 'column',
        gap: '2px',
    },
    kpiLabel: {
        fontSize: '0.65rem',
        fontWeight: '700',
        color: 'var(--text-muted)',
        textTransform: 'uppercase',
        letterSpacing: '0.08em',
    },
    kpiValue: {
        fontSize: '1.6rem',
        fontWeight: '900',
        lineHeight: 1,
    },
    wsBotRow: {
        display: 'grid',
        gridTemplateColumns: '1fr 1fr',
        gap: '1.25rem',
    },
    wsPanel: {
        padding: '1.5rem',
        display: 'flex',
        flexDirection: 'column',
        gap: '1.25rem',
    },
    wsPanelHeader: {
        display: 'flex',
        alignItems: 'center',
        gap: '10px',
        marginBottom: '0.25rem',
    },
    wsPanelTitle: {
        fontSize: '0.85rem',
        fontWeight: '800',
        color: 'var(--text-primary)',
        textTransform: 'uppercase',
        letterSpacing: '0.06em',
    },
    breakdownRow: {
        display: 'flex',
        flexDirection: 'column',
        gap: '6px',
    },
    breakdownMeta: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
    },
    breakdownDot: {
        width: '8px',
        height: '8px',
        borderRadius: '50%',
        flexShrink: 0,
    },
    breakdownLabel: {
        fontSize: '0.75rem',
        color: 'var(--text-secondary)',
        fontWeight: '600',
    },
    breakdownCount: {
        fontSize: '0.75rem',
        fontWeight: '800',
        marginLeft: 'auto',
    },
    barTrack: {
        height: '6px',
        borderRadius: '999px',
        background: 'rgba(255,255,255,0.07)',
        overflow: 'hidden',
    },
    barFill: {
        height: '100%',
        borderRadius: '999px',
        transition: 'width 0.6s ease',
    },
    ticketStatGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(3, 1fr)',
        gap: '1rem',
        flex: 1,
    },
    ticketStatItem: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        background: 'rgba(255,255,255,0.04)',
        borderRadius: '10px',
        padding: '0.6rem 0.5rem',
        border: '1px solid var(--glass-border)',
    },
    ticketStatNum: {
        fontSize: '1.4rem',
        fontWeight: '900',
        lineHeight: 1,
    },
    ticketStatLabel: {
        fontSize: '0.6rem',
        color: 'var(--text-muted)',
        fontWeight: '700',
        textTransform: 'uppercase',
        marginTop: '4px',
    },
    recentTicketsSection: {
        marginTop: '1.5rem',
        padding: '1rem',
        display: 'flex',
        flexDirection: 'column',
        gap: '1rem',
    },
    sectionHeader: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
    },
    sectionIndicator: {
        width: '4px',
        height: '24px',
        background: 'var(--accent-blue)',
        borderRadius: '2px',
    },
    scrollContainer: {
        display: 'flex',
        flexDirection: 'column',
        gap: '0.75rem',
        maxHeight: '400px',
        overflowY: 'auto',
        paddingRight: '8px',
    },
    ticketDetailCard: {
        background: 'rgba(255, 255, 255, 0.03)',
        border: '1px solid var(--glass-border)',
        borderRadius: '12px',
        padding: '1rem',
        display: 'flex',
        flexDirection: 'column',
        gap: '0.75rem',
        cursor: 'pointer',
    },
    ticketCardHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    ticketIdText: {
        fontSize: '1rem',
        fontWeight: '900',
        color: 'var(--accent-blue)',
        fontFamily: 'monospace',
    },
    ticketCardRow: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    ticketRowLabel: {
        fontSize: '0.8rem',
        color: 'var(--text-muted)',
    },
    ticketRowValue: {
        fontSize: '0.8rem',
        fontWeight: '800',
        color: 'var(--text-primary)',
        textTransform: 'uppercase',
    },
    descriptionBox: {
        background: 'rgba(0, 0, 0, 0.2)',
        padding: '8px',
        borderRadius: '6px',
        fontSize: '0.75rem',
        color: 'var(--text-primary)',
        lineHeight: '1.4',
    },
    ticketCardFooter: {
        display: 'flex',
        justifyContent: 'flex-end',
        fontSize: '0.7rem',
        color: 'var(--text-muted)',
    },
    raisedAt: {
        fontStyle: 'italic',
    },
    modalHeaderRight: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
    },
    ticketActions: {
        display: 'flex',
        justifyContent: 'flex-end',
        gap: '0.75rem',
        marginTop: '0.5rem',
    },
    approveBtn: {
        background: '#10b981',
        color: 'white',
        border: 'none',
        padding: '0.4rem 1.25rem',
        borderRadius: '6px',
        fontWeight: '900',
        fontSize: '0.65rem',
        cursor: 'pointer',
        transition: 'all 0.2s ease',
    },
    rejectCardBtn: {
        background: 'rgba(239, 68, 68, 0.1)',
        color: '#ef4444',
        border: '1px solid rgba(239, 68, 68, 0.2)',
        padding: '0.4rem 1.25rem',
        borderRadius: '6px',
        fontWeight: '900',
        fontSize: '0.65rem',
        cursor: 'pointer',
    },
};
